### ISSUE TITLE
How to use hdfs_to_cos_tools in Hadoop of CDH version

### ISSUE THREAD

**Issue by wudidiandian** [tencentyun/hdfs_to_cos_tools#5]
hi guys:
     My cluster version is Hadoop 3.0.0-cdh6.1.0,i put the core-site.xml file in the conf directory according to the readme operation. The command "sh hdfs_to_cos_cmd -- hdfs_path ..." was executed incorrectly，the error message is "
Exception in thread "main" java.lang.IllegalArgumentException: java.net.UnknownHostException: nameservice1
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:378)
	at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:310)
	at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:678)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2653)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:368)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:170)
	at com.qcloud.hdfs_to_cos.ConfigReader.buildHdfsFS(ConfigReader.java:143)
	at com.qcloud.hdfs_to_cos.ConfigReader.init(ConfigReader.java:51)
	at com.qcloud.hdfs_to_cos.ConfigReader.<init>(ConfigReader.java:47)
	at com.qcloud.hdfs_to_cos.App.main(App.java:66)
Caused by: java.net.UnknownHostException: nameservice1
	... 13 more

" 
So I put the hdfs-site.xml file in the conf directory as well.  but another error was prompted.
" config error. config appid is required"

So now is it okay to configure my Hadoop part? The new error is just appid problem?

**Comment by wudidiandian** [comment]
Actually, I don't see the corresponding log in the log directory. Isn't the log in the log directory a log that executes the hdfs_to_cos_tools command?

**Comment by wudidiandian** [comment]
I have solved this problem.First you need to put hdfs-site.xml in the conf directory,and you should add the appid configuration to the cos_info.conf file, even if your bucket contains appid, you still need to add "appid = xxxxxxxxx". Personally, I feel that the official API is too detailed.
